name: TestTracker UI Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-tests:
    runs-on: ubuntu-latest

    env:
      ANDROID_API_LEVEL: 31
      DEVICE_NAME: emulator-5554
      EMULATOR_IMAGE: system-images;android-${{ env.ANDROID_API_LEVEL }};default;x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "11"

      - name: Install Android SDK & Create AVD
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          arch: x86_64
          target: default
          force-avd-creation: true

      - name: Start Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          arch: x86_64
          target: default
          emulator-options: -no-window -gpu off

      - name: Wait for emulator to be ready
        run: adb wait-for-device

      - name: Unlock Android screen
        run: |
          adb shell input keyevent 82

      - name: Install npm dependencies
        run: npm ci

      - name: Run WebdriverIO tests on Android
        run: |
          npx wdio run wdio.conf.js --spec './test/specs/testcases/*.spec.js'

      - name: Shutdown emulator
        if: always()
        run: adb -s ${{ env.DEVICE_NAME }} emu kill
